import type { Collection, Exif, Photo } from "./types";

/**
 * Demo Mode content.
 *
 * When no Supabase credentials are present the entire site falls back to this
 * dataset so the layout, motion and lightbox can be evaluated — and so the
 * project builds and deploys cleanly before the backend exists. Every record
 * mirrors the shape returned by the real database.
 *
 * Placeholder imagery is served by Lorem Picsum via stable seeds. Replace it by
 * connecting Supabase; nothing here is referenced once credentials are set.
 */

function placeholder(seed: string, width: number, height: number): string {
  return `https://picsum.photos/seed/${seed}/${width}/${height}`;
}

export const demoCollections: Collection[] = [
  {
    slug: "landscapes",
    title: "Landscapes",
    titleZh: "风景",
    description:
      "Long exposures and long walks. Work made in places that take days to reach and minutes to photograph.",
    sortOrder: 1,
    photoCount: 0,
    coverSrc: null,
    coverBlurDataUrl: null,
  },
  {
    slug: "events",
    title: "Events",
    titleZh: "活动纪实",
    description:
      "Documentary coverage of ceremonies, performances and the unrepeatable seconds in between.",
    sortOrder: 2,
    photoCount: 0,
    coverSrc: null,
    coverBlurDataUrl: null,
  },
  {
    slug: "portrait",
    title: "Portraits",
    titleZh: "人像",
    description: "Available light, patient subjects, and the search for a single honest expression.",
    sortOrder: 3,
    photoCount: 0,
    coverSrc: null,
    coverBlurDataUrl: null,
  },
  {
    slug: "street",
    title: "Street",
    titleZh: "街头",
    description: "The city as it is, without arrangement. Mostly after rain, mostly at dusk.",
    sortOrder: 4,
    photoCount: 0,
    coverSrc: null,
    coverBlurDataUrl: null,
  },
  {
    slug: "architecture",
    title: "Architecture",
    titleZh: "建筑",
    description: "Structure, repetition and the geometry that concrete takes on when light rakes it.",
    sortOrder: 5,
    photoCount: 0,
    coverSrc: null,
    coverBlurDataUrl: null,
  },
];

type DemoSeed = {
  seed: string;
  title: string;
  caption?: string;
  location: string;
  collection: string;
  width: number;
  height: number;
  tags: string[];
  takenAt: string;
  featured?: boolean;
  exif: Exif;
};

const SEEDS: DemoSeed[] = [
  /* ----------------------------- Landscapes ----------------------------- */
  {
    seed: "lumen-granite-fog",
    title: "Granite and Fog",
    caption: "Forty minutes of waiting for the cloud to lift off the ridge line.",
    location: "Torres del Paine, Chile",
    collection: "landscapes",
    width: 1600,
    height: 1067,
    tags: ["mountain", "fog", "dawn"],
    takenAt: "2025-03-14T06:12:00.000Z",
    featured: true,
    exif: {
      camera: "Sony α7R V",
      lens: "FE 16-35mm F2.8 GM",
      focalLength: "16mm",
      focalLengthMm: 16,
      aperture: "f/8",
      shutter: "1/250s",
      iso: 100,
      whiteBalance: "Auto",
      meteringMode: "Pattern",
      colorSpace: "sRGB",
      dateTaken: "2025-03-14T06:12:00.000Z",
    },
  },
  {
    seed: "lumen-long-valley",
    title: "The Long Valley",
    location: "Yosemite, California",
    collection: "landscapes",
    width: 1600,
    height: 900,
    tags: ["valley", "panorama", "autumn"],
    takenAt: "2024-10-02T17:40:00.000Z",
    featured: true,
    exif: {
      camera: "Canon EOS R5",
      lens: "RF 24-70mm F2.8L IS USM",
      focalLength: "24-70mm",
      focalLengthMm: 35,
      aperture: "f/11",
      shutter: "1/125s",
      iso: 200,
      dateTaken: "2024-10-02T17:40:00.000Z",
    },
  },
  {
    seed: "lumen-salt-silence",
    title: "Salt and Silence",
    caption: "The mirror only appears for about ninety minutes after rain.",
    location: "Salar de Uyuni, Bolivia",
    collection: "landscapes",
    width: 1067,
    height: 1600,
    tags: ["reflection", "minimal", "altitude"],
    takenAt: "2025-01-22T05:05:00.000Z",
    exif: {
      camera: "Nikon Z 8",
      lens: "NIKKOR Z 14-24mm f/2.8 S",
      focalLength: "15mm",
      focalLengthMm: 15,
      aperture: "f/5.6",
      shutter: "1/60s",
      iso: 64,
      exposureCompensation: "+0.7 EV",
      dateTaken: "2025-01-22T05:05:00.000Z",
    },
  },
  {
    seed: "lumen-north-nowhere",
    title: "North of Nowhere",
    location: "Lofoten, Norway",
    collection: "landscapes",
    width: 1600,
    height: 1067,
    tags: ["arctic", "snow", "blue hour"],
    takenAt: "2024-02-08T15:20:00.000Z",
    exif: {
      camera: "Sony α7R V",
      lens: "FE 70-200mm F2.8 GM OSS II",
      focalLength: "70-200mm",
      focalLengthMm: 135,
      aperture: "f/4",
      shutter: "1/400s",
      iso: 320,
      dateTaken: "2024-02-08T15:20:00.000Z",
    },
  },
  {
    seed: "lumen-dune-light",
    title: "Dune Light",
    location: "Sossusvlei, Namibia",
    collection: "landscapes",
    width: 1280,
    height: 1600,
    tags: ["desert", "shadow", "minimal"],
    takenAt: "2024-08-19T07:15:00.000Z",
    exif: {
      camera: "Fujifilm GFX 100 II",
      lens: "GF 45-100mm F4 R LM OIS WR",
      focalLength: "45-100mm",
      focalLengthMm: 100,
      aperture: "f/9",
      shutter: "1/500s",
      iso: 100,
      dateTaken: "2024-08-19T07:15:00.000Z",
    },
  },
  {
    seed: "lumen-glacier-tongue",
    title: "Glacier Tongue",
    location: "Vatnajökull, Iceland",
    collection: "landscapes",
    width: 1600,
    height: 1067,
    tags: ["ice", "aerial", "abstract"],
    takenAt: "2024-06-30T11:48:00.000Z",
    exif: {
      camera: "DJI Mavic 3 Pro",
      lens: "Hasselblad 24mm",
      focalLength: "24mm",
      focalLengthMm: 24,
      aperture: "f/2.8",
      shutter: "1/1200s",
      iso: 100,
      dateTaken: "2024-06-30T11:48:00.000Z",
    },
  },
  {
    seed: "lumen-still-water",
    title: "Still Water",
    location: "Lake Bled, Slovenia",
    collection: "landscapes",
    width: 1600,
    height: 1280,
    tags: ["lake", "mist", "morning"],
    takenAt: "2024-09-11T06:02:00.000Z",
    exif: {
      camera: "Sony α7R V",
      lens: "FE 24-70mm F2.8 GM II",
      focalLength: "24-70mm",
      focalLengthMm: 50,
      aperture: "f/5.6",
      shutter: "1/60s",
      iso: 100,
      dateTaken: "2024-09-11T06:02:00.000Z",
    },
  },

  /* ------------------------------- Events ------------------------------- */
  {
    seed: "lumen-first-dance",
    title: "First Dance",
    location: "Kyoto, Japan",
    collection: "events",
    width: 1600,
    height: 1067,
    tags: ["wedding", "documentary", "low light"],
    takenAt: "2024-11-16T19:32:00.000Z",
    featured: true,
    exif: {
      camera: "Sony α7 IV",
      lens: "FE 35mm F1.4 GM",
      focalLength: "35mm",
      focalLengthMm: 35,
      aperture: "f/1.4",
      shutter: "1/125s",
      iso: 3200,
      whiteBalance: "Manual",
      dateTaken: "2024-11-16T19:32:00.000Z",
    },
  },
  {
    seed: "lumen-confetti",
    title: "Confetti",
    location: "Lisbon, Portugal",
    collection: "events",
    width: 1067,
    height: 1600,
    tags: ["celebration", "candid", "motion"],
    takenAt: "2024-05-25T13:10:00.000Z",
    exif: {
      camera: "Canon EOS R6 II",
      lens: "RF 85mm F1.2L USM",
      focalLength: "85mm",
      focalLengthMm: 85,
      aperture: "f/1.8",
      shutter: "1/1000s",
      iso: 400,
      dateTaken: "2024-05-25T13:10:00.000Z",
    },
  },
  {
    seed: "lumen-backstage",
    title: "Backstage, Act II",
    caption: "Shot from the wings during the second interval.",
    location: "Vienna, Austria",
    collection: "events",
    width: 1600,
    height: 1067,
    tags: ["theatre", "backstage", "available light"],
    takenAt: "2025-02-07T20:55:00.000Z",
    exif: {
      camera: "Leica SL3",
      lens: "APO-Summicron-SL 35mm f/2 ASPH",
      focalLength: "35mm",
      focalLengthMm: 35,
      aperture: "f/2",
      shutter: "1/60s",
      iso: 6400,
      dateTaken: "2025-02-07T20:55:00.000Z",
    },
  },
  {
    seed: "lumen-finish-line",
    title: "The Finish Line",
    location: "Boston, Massachusetts",
    collection: "events",
    width: 1600,
    height: 900,
    tags: ["sport", "reportage", "crowd"],
    takenAt: "2025-04-21T14:22:00.000Z",
    exif: {
      camera: "Canon EOS R3",
      lens: "RF 70-200mm F2.8L IS USM",
      focalLength: "70-200mm",
      focalLengthMm: 200,
      aperture: "f/2.8",
      shutter: "1/2000s",
      iso: 800,
      dateTaken: "2025-04-21T14:22:00.000Z",
    },
  },
  {
    seed: "lumen-candlelit",
    title: "Candlelit Procession",
    location: "Seville, Spain",
    collection: "events",
    width: 1280,
    height: 1600,
    tags: ["night", "tradition", "handheld"],
    takenAt: "2025-04-04T22:40:00.000Z",
    exif: {
      camera: "Sony α7S III",
      lens: "FE 35mm F1.4 GM",
      focalLength: "35mm",
      focalLengthMm: 35,
      aperture: "f/1.4",
      shutter: "1/80s",
      iso: 12800,
      dateTaken: "2025-04-04T22:40:00.000Z",
    },
  },
  {
    seed: "lumen-sound-check",
    title: "Sound Check",
    location: "Reykjavík, Iceland",
    collection: "events",
    width: 1600,
    height: 1067,
    tags: ["music", "monochrome", "stage light"],
    takenAt: "2024-12-01T17:05:00.000Z",
    exif: {
      camera: "Nikon Z 6III",
      lens: "NIKKOR Z 50mm f/1.2 S",
      focalLength: "50mm",
      focalLengthMm: 50,
      aperture: "f/1.2",
      shutter: "1/160s",
      iso: 4000,
      dateTaken: "2024-12-01T17:05:00.000Z",
    },
  },

  /* ------------------------------ Portraits ----------------------------- */
  {
    seed: "lumen-mira-window",
    title: "Mira, Window Light",
    location: "Studio, Shanghai",
    collection: "portrait",
    width: 1280,
    height: 1600,
    tags: ["portrait", "window light", "natural"],
    takenAt: "2025-05-09T15:30:00.000Z",
    featured: true,
    exif: {
      camera: "Sony α7R V",
      lens: "FE 85mm F1.4 GM II",
      focalLength: "85mm",
      focalLengthMm: 85,
      aperture: "f/1.6",
      shutter: "1/200s",
      iso: 200,
      dateTaken: "2025-05-09T15:30:00.000Z",
    },
  },
  {
    seed: "lumen-study-grey",
    title: "Study in Grey",
    location: "Hangzhou, China",
    collection: "portrait",
    width: 1067,
    height: 1600,
    tags: ["portrait", "editorial", "monochrome"],
    takenAt: "2025-01-30T11:12:00.000Z",
    exif: {
      camera: "Leica M11 Monochrom",
      lens: "Summilux-M 50mm f/1.4 ASPH",
      focalLength: "50mm",
      focalLengthMm: 50,
      aperture: "f/2",
      shutter: "1/250s",
      iso: 400,
      dateTaken: "2025-01-30T11:12:00.000Z",
    },
  },
  {
    seed: "lumen-violinist",
    title: "The Violinist",
    location: "Berlin, Germany",
    collection: "portrait",
    width: 1600,
    height: 1067,
    tags: ["portrait", "musician", "environmental"],
    takenAt: "2024-03-18T16:44:00.000Z",
    exif: {
      camera: "Fujifilm X-T5",
      lens: "XF 56mmF1.2 R WR",
      focalLength: "56mm",
      focalLengthMm: 56,
      focalLength35mm: 84,
      aperture: "f/1.2",
      shutter: "1/180s",
      iso: 500,
      dateTaken: "2024-03-18T16:44:00.000Z",
    },
  },
  {
    seed: "lumen-golden-hour-four",
    title: "Golden Hour, No. 4",
    location: "Santorini, Greece",
    collection: "portrait",
    width: 1400,
    height: 1400,
    tags: ["portrait", "square", "backlight"],
    takenAt: "2024-07-12T19:58:00.000Z",
    exif: {
      camera: "Sony α7 IV",
      lens: "FE 135mm F1.8 GM",
      focalLength: "135mm",
      focalLengthMm: 135,
      aperture: "f/1.8",
      shutter: "1/1600s",
      iso: 100,
      exposureCompensation: "+1.0 EV",
      dateTaken: "2024-07-12T19:58:00.000Z",
    },
  },

  /* -------------------------------- Street ------------------------------ */
  {
    seed: "lumen-crossing",
    title: "Crossing",
    location: "Shibuya, Tokyo",
    collection: "street",
    width: 1600,
    height: 1067,
    tags: ["street", "night", "neon"],
    takenAt: "2024-04-06T19:20:00.000Z",
    featured: true,
    exif: {
      camera: "Ricoh GR IIIx",
      lens: "GR 40mm f/2.8",
      focalLength: "40mm",
      focalLengthMm: 40,
      aperture: "f/2.8",
      shutter: "1/125s",
      iso: 1600,
      dateTaken: "2024-04-06T19:20:00.000Z",
    },
  },
  {
    seed: "lumen-rain-six",
    title: "Rain, 6pm",
    location: "Central, Hong Kong",
    collection: "street",
    width: 1067,
    height: 1600,
    tags: ["street", "rain", "reflection"],
    takenAt: "2024-06-14T18:05:00.000Z",
    exif: {
      camera: "Leica Q3",
      lens: "Summilux 28mm f/1.7 ASPH",
      focalLength: "28mm",
      focalLengthMm: 28,
      aperture: "f/2.8",
      shutter: "1/250s",
      iso: 1250,
      dateTaken: "2024-06-14T18:05:00.000Z",
    },
  },
  {
    seed: "lumen-umbrella-study",
    title: "Umbrella Study",
    location: "Osaka, Japan",
    collection: "street",
    width: 1600,
    height: 1280,
    tags: ["street", "graphic", "overhead"],
    takenAt: "2024-04-11T12:35:00.000Z",
    exif: {
      camera: "Fujifilm X100VI",
      lens: "Fujinon 23mm f/2",
      focalLength: "23mm",
      focalLengthMm: 23,
      focalLength35mm: 35,
      aperture: "f/5.6",
      shutter: "1/500s",
      iso: 320,
      dateTaken: "2024-04-11T12:35:00.000Z",
    },
  },
  {
    seed: "lumen-late-delivery",
    title: "Late Delivery",
    location: "Taipei, Taiwan",
    collection: "street",
    width: 1600,
    height: 900,
    tags: ["street", "cinematic", "motion"],
    takenAt: "2025-03-02T21:15:00.000Z",
    exif: {
      camera: "Sony α7C II",
      lens: "FE 24-70mm F2.8 GM II",
      focalLength: "24-70mm",
      focalLengthMm: 70,
      aperture: "f/2.8",
      shutter: "1/60s",
      iso: 2500,
      dateTaken: "2025-03-02T21:15:00.000Z",
    },
  },

  /* ----------------------------- Architecture --------------------------- */
  {
    seed: "lumen-concrete-cathedral",
    title: "Concrete Cathedral",
    location: "Tokyo, Japan",
    collection: "architecture",
    width: 1067,
    height: 1600,
    tags: ["architecture", "brutalism", "symmetry"],
    takenAt: "2024-04-08T10:40:00.000Z",
    exif: {
      camera: "Sony α7R V",
      lens: "FE 16-35mm F2.8 GM",
      focalLength: "16-35mm",
      focalLengthMm: 16,
      aperture: "f/8",
      shutter: "1/200s",
      iso: 100,
      dateTaken: "2024-04-08T10:40:00.000Z",
    },
  },
  {
    seed: "lumen-stairwell",
    title: "Stairwell",
    location: "Rotterdam, Netherlands",
    collection: "architecture",
    width: 1280,
    height: 1600,
    tags: ["architecture", "spiral", "geometry"],
    takenAt: "2024-09-27T09:55:00.000Z",
    exif: {
      camera: "Canon EOS R5",
      lens: "RF 14-35mm F4L IS USM",
      focalLength: "14-35mm",
      focalLengthMm: 14,
      aperture: "f/7.1",
      shutter: "1/80s",
      iso: 400,
      dateTaken: "2024-09-27T09:55:00.000Z",
    },
  },
  {
    seed: "lumen-grid",
    title: "Grid",
    location: "Singapore",
    collection: "architecture",
    width: 1400,
    height: 1400,
    tags: ["architecture", "facade", "repetition"],
    takenAt: "2024-12-19T16:08:00.000Z",
    exif: {
      camera: "Nikon Z 8",
      lens: "NIKKOR Z 100-400mm f/4.5-5.6 VR S",
      focalLength: "100-400mm",
      focalLengthMm: 400,
      aperture: "f/8",
      shutter: "1/320s",
      iso: 200,
      dateTaken: "2024-12-19T16:08:00.000Z",
    },
  },
  {
    seed: "lumen-negative-space",
    title: "Negative Space",
    location: "Seoul, South Korea",
    collection: "architecture",
    width: 1600,
    height: 1067,
    tags: ["architecture", "minimal", "high key"],
    takenAt: "2025-02-21T14:02:00.000Z",
    exif: {
      camera: "Sony α7R V",
      lens: "FE 24-70mm F2.8 GM II",
      focalLength: "24-70mm",
      focalLengthMm: 45,
      aperture: "f/10",
      shutter: "1/400s",
      iso: 100,
      dateTaken: "2025-02-21T14:02:00.000Z",
    },
  },
];

/** Photos materialised from the seed list above. */
export const demoPhotos: Photo[] = SEEDS.map((seed, index) => ({
  id: `demo-${String(index + 1).padStart(3, "0")}`,
  storagePath: placeholder(seed.seed, seed.width, seed.height),
  originalPath: null,
  src: placeholder(seed.seed, seed.width, seed.height),
  fileName: `${seed.seed}.jpg`,
  width: seed.width,
  height: seed.height,
  blurDataUrl: null,
  dominantColor: null,
  title: seed.title,
  caption: seed.caption ?? null,
  location: seed.location,
  collection: seed.collection,
  tags: seed.tags,
  exif: seed.exif,
  featured: seed.featured ?? false,
  sortOrder: index,
  takenAt: seed.takenAt,
  createdAt: seed.takenAt,
  updatedAt: seed.takenAt,
}));

/** Collections enriched with cover art and counts, as the repository returns them. */
export const demoCollectionsWithCovers: Collection[] = demoCollections.map((collection) => {
  const members = demoPhotos.filter((photo) => photo.collection === collection.slug);
  return {
    ...collection,
    photoCount: members.length,
    coverSrc: members[0]?.src ?? null,
    coverBlurDataUrl: members[0]?.blurDataUrl ?? null,
  };
});
